# Generated by Django 5.2.5 on 2025-09-02 14:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100)),
                ('localization', models.CharField(choices=[('0-A', '0-A'), ('1-A', '1-A'), ('2-A', '2-A'), ('3-A', '3-A'), ('4-A', '4-A'), ('0-B', '0-B'), ('1-B', '1-B'), ('2-B', '2-B'), ('3-B', '3-B'), ('4-B', '4-B')], default='0-A', max_length=10)),
                ('quantity', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='InventoryManagement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('entry', 'Entry'), ('exit', 'Exit'), ('transfer', 'Transfer')], default='entry', max_length=10)),
                ('localization', models.CharField(choices=[('0-A', '0-A'), ('1-A', '1-A'), ('2-A', '2-A'), ('3-A', '3-A'), ('4-A', '4-A'), ('0-B', '0-B'), ('1-B', '1-B'), ('2-B', '2-B'), ('3-B', '3-B'), ('4-B', '4-B')], default='0-A', max_length=10)),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ventory.product')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ventory.user')),
            ],
        ),
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_location', models.CharField(max_length=20)),
                ('to_location', models.CharField(max_length=20)),
                ('quantity', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('mov_in', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='ventory.inventorymanagement')),
                ('mov_out', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='ventory.inventorymanagement')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ventory.product')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ventory.user')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='username',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ventory.user'),
        ),
        migrations.CreateModel(
            name='Stock_balance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('localization', models.CharField(choices=[('0-A', '0-A'), ('1-A', '1-A'), ('2-A', '2-A'), ('3-A', '3-A'), ('4-A', '4-A'), ('0-B', '0-B'), ('1-B', '1-B'), ('2-B', '2-B'), ('3-B', '3-B'), ('4-B', '4-B')], default='0-A', max_length=10)),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ventory.product')),
            ],
            options={
                'unique_together': {('product', 'localization')},
            },
        ),
    ]
